name: HeadHunter
main: com.github.dublekfx.HeadHunter.HeadHunter
version: 0.1
commands:
  hh:
    description: This is the command to set head probabilities
    usage: /hh <reload/display/looting> <1/2/3> <probability>
    permission: headhunter.set
    permission-message: You are not op!
permissions:
  headhunter.set:
    description: Permits ops to set head drop probability
    default: op